server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: "root"
    username: "root"
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
mybatis-plus:
  type-aliases-package: com.scujj.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
   com.scujj.mapper: info
   com.scujj.mapper.LeaveMapper: debug